name: s_context_menu
description: A professional highly-featured Flutter context menu widget built from scratch, offering advanced customization, accessibility, and smooth animations.
issue_tracker: https://github.com/SoundSliced/s_context_menu/issues
repository: https://github.com/SoundSliced/s_context_menu
version: 2.0.0
homepage: https://github.com/SoundSliced/s_context_menu

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  s_packages: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true